/*
 * 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package kp.rollingcube.ce.ui;

import java.nio.file.Path;
import javax.swing.JDialog;
import kp.rollingcube.ce.campaign.Campaign;
import kp.rollingcube.ce.campaign.CampaingLoadSaveState;
import kp.rollingcube.ce.utils.UIUtils;
import lombok.NonNull;

/**
 *
 * @author Marc
 */
public class CampaignLoader extends JDialog
{
    private final @NonNull CampaignEditor editor;
    private final @NonNull CampaingLoadSaveState state;
    
    private CampaignLoader(CampaignEditor editor, CampaingLoadSaveState state)
    {
        super(editor, true);
        initComponents();
        
        this.editor = editor;
        this.state = state;
        
        state.setOnStartCallback(this::onStart);
        state.setOnUpdateCallback(this::onUpdate);
        state.setOnFinishCallback(this::onFinish);
        
        infoLabel.setText("");
        progressBar.setValue(0);
        progressBar.setMaximum(100);
        progressBar.setMinimum(0);
        
        UIUtils.focus(this);
    }
    
    private void onStart(int total, int current, String text)
    {
        progressBar.setValue(current);
        progressBar.setMaximum(total);
        infoLabel.setText(text);
    }
    
    private void onUpdate(int total, int current, String text)
    {
        progressBar.setValue(current);
        progressBar.setMaximum(total);
        infoLabel.setText(text);
    }
    
    private void onFinish(CampaingLoadSaveState.OperationResult result)
    {
        int value = Math.max(1, progressBar.getMaximum());
        progressBar.setValue(value);
        progressBar.setMaximum(value);
        
        if(result.hasError())
        {
            infoLabel.setText("An error has been ocurred");
            Notify.error(editor, result.getError());
        }
        
        dispose();
    }
    
    public static Campaign loadCampaign(CampaignEditor editor, Path path)
    {
        var state = Campaign.load(path);
        var popup = new CampaignLoader(editor, state);
        popup.setVisible(true);
        return state.getCampaign();
    }
    
    public static void saveCampaign(CampaignEditor editor, Campaign campaign, Path path)
    {
        var state = campaign.save(path);
        var popup = new CampaignLoader(editor, state);
        popup.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        infoLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        state.start();
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
