/*
 * 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kp.rollingcube.ce.ui;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;
import kp.rollingcube.ce.campaign.IndexedLevel;
import kp.rollingcube.ce.utils.Thumbnail;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Marc
 * @param <T>
 */
public class IndexableLevelCard<T extends IndexedLevel> extends JPanel
{
    @Getter @Setter
    private T level;
    private Thumbnail thumbnail;
    
    @Getter @Setter
    private EventsListener<T> listener;
    
    public IndexableLevelCard()
    {
        initComponents();
    }
    
    public void update()
    {
        if(level == null)
        {
            indexField.setText("?");
            fruitField.setText("---");
            fruitField.setForeground(Color.RED);
            secretExitField.setText("---");
            secretExitField.setForeground(Color.RED);
            upButton.setEnabled(false);
            downButton.setEnabled(false);
            deleteButton.setEnabled(false);
            thumbnail = null;
            thumbnailPanel.repaint();
        }
        else
        {
            indexField.setText(Integer.toString(level.getIndex() + 1));
            
            if(level.hasFruit())
            {
                fruitField.setText("Yes");
                fruitField.setForeground(Color.GREEN);
            }
            else
            {
                fruitField.setText("No");
                fruitField.setForeground(Color.RED);
            }
            
            var secretTag = level.getSecretExitLevelTag();
            if(secretTag.isPresent())
            {
                secretExitField.setText(secretTag.get());
                secretExitField.setForeground(Color.GREEN);
            }
            else
            {
                secretExitField.setText("---");
                secretExitField.setForeground(Color.RED);
            }
            
            upButton.setEnabled(level.getIndex() > 0);
            downButton.setEnabled(level.getIndex() < (getLevelsCount() - 1));
            deleteButton.setEnabled(true);
            
            thumbnail = new Thumbnail(level.getThumbnail(), thumbnailPanel::getWidth , thumbnailPanel::getHeight,
                    thumbnailImage -> thumbnailPanel.repaint());
        }
        
        repaint();
    }
    
    private int getLevelsCount()
    {
        var episode = level.getEpisode();
        switch(level.getType())
        {
            case NORMAL: return episode.getNormalLevelsCount();
            case BONUS: return episode.getBonusLevelsCount();
            default: return 0;
        }
    }
    
    private void drawThumbnail(Graphics g)
    {
        if(thumbnail != null)
            thumbnail.draw(g, thumbnailPanel);
    }
    
    public static interface EventsListener<T extends IndexedLevel>
    {
        void onDelete(T level);
        void onUp(T level);
        void onDown(T level);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thumbnailPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                drawThumbnail(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        indexField = new javax.swing.JTextField();
        downButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        fruitField = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        secretExitField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout thumbnailPanelLayout = new javax.swing.GroupLayout(thumbnailPanel);
        thumbnailPanel.setLayout(thumbnailPanelLayout);
        thumbnailPanelLayout.setHorizontalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        thumbnailPanelLayout.setVerticalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Index:");

        indexField.setEditable(false);
        indexField.setFocusable(false);

        downButton.setText("Down");

        upButton.setText("Up");

        fruitField.setText("No");

        jLabel3.setText("Has fruit:");

        secretExitField.setText("---");

        jLabel5.setText("Secret exit:");

        deleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbnailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indexField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(downButton)
                            .addComponent(upButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fruitField))
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secretExitField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(indexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(fruitField)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secretExitField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downButton)
                            .addComponent(deleteButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton downButton;
    private javax.swing.JLabel fruitField;
    private javax.swing.JTextField indexField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel secretExitField;
    private javax.swing.JPanel thumbnailPanel;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
