package kp.rollingcube.ce.ui;

import java.awt.Graphics;
import javax.swing.JPanel;
import kp.rollingcube.ce.campaign.SecretLevel;
import kp.rollingcube.ce.utils.Thumbnail;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Marc
 */
public class SecretLevelCard extends JPanel
{
    @Getter @Setter
    private SecretLevel level;
    private Thumbnail thumbnail;
    
    //private final StringTextFieldManager aliasHandler;
    
    @Getter @Setter
    private EventsListener listener;
    
    public SecretLevelCard()
    {
        initComponents();
        aliasLabel.setVisible(false);
        aliasField.setVisible(false);
        
        //aliasHandler = new StringTextFieldManager(aliasField, this::setLevelAlias, this::getLevelAlias);
    }
    
    public void update()
    {
        if(level == null)
        {
            nameField.setText("");
            oneTryBox.setSelected(false);
            penaltyBox.setSelected(false);
            //aliasHandler.bind();
            thumbnail = null;
            thumbnailPanel.repaint();
        }
        else
        {
            nameField.setText(level.getName());
            oneTryBox.setSelected(level.isOneTry());
            penaltyBox.setSelected(level.isPenalty());
            //aliasHandler.bind();
            
            thumbnail = new Thumbnail(level.getThumbnail(), thumbnailPanel::getWidth , thumbnailPanel::getHeight,
                    thumbnailImage -> thumbnailPanel.repaint());
        }
        
        repaint();
    }
    
    private void drawThumbnail(Graphics g)
    {
        if(thumbnail != null)
            thumbnail.draw(g, thumbnailPanel);
    }
    
    //private String getLevelAlias() { return level != null ? level.getAlias() : ""; }
    //private void setLevelAlias(String value) { if(level != null) level.setAlias(value); }
    
    @FunctionalInterface
    public static interface EventsListener
    {
        void onDelete(SecretLevel level);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thumbnailPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                drawThumbnail(g);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        changeNameButton = new javax.swing.JButton();
        oneTryBox = new javax.swing.JCheckBox();
        penaltyBox = new javax.swing.JCheckBox();
        aliasLabel = new javax.swing.JLabel();
        aliasField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout thumbnailPanelLayout = new javax.swing.GroupLayout(thumbnailPanel);
        thumbnailPanel.setLayout(thumbnailPanelLayout);
        thumbnailPanelLayout.setHorizontalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        thumbnailPanelLayout.setVerticalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Name:");

        nameField.setEditable(false);
        nameField.setFocusable(false);

        changeNameButton.setText("Change Name");
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        oneTryBox.setText("One Attempt");
        oneTryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTryBoxActionPerformed(evt);
            }
        });

        penaltyBox.setText("Enable Penalty");
        penaltyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penaltyBoxActionPerformed(evt);
            }
        });

        aliasLabel.setText("Alias:");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbnailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aliasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aliasField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oneTryBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(penaltyBox)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeNameButton)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneTryBox)
                            .addComponent(penaltyBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aliasLabel)
                            .addComponent(aliasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(listener != null)
            listener.onDelete(level);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oneTryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTryBoxActionPerformed
        level.setOneTry(oneTryBox.isSelected());
    }//GEN-LAST:event_oneTryBoxActionPerformed

    private void penaltyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penaltyBoxActionPerformed
        level.setPenalty(penaltyBox.isSelected());
    }//GEN-LAST:event_penaltyBoxActionPerformed

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        if(level == null)
            return;
        
        var name = Notify.askName(this, "Change Secret Level Name", "Enter a new name for the secret level");
        if(name.isEmpty())
            return;
        
        try
        {
            level.getEpisode().changeSecretLevelName(level.getName(), name.get());
            update();
        }
        catch(IllegalArgumentException ex)
        {
            Notify.ferror(
                    this,
                    null,
                    "An error occurred while changing the episode name: %s",
                    ex.getLocalizedMessage()
            );
        }
    }//GEN-LAST:event_changeNameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aliasField;
    private javax.swing.JLabel aliasLabel;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox oneTryBox;
    private javax.swing.JCheckBox penaltyBox;
    private javax.swing.JPanel thumbnailPanel;
    // End of variables declaration//GEN-END:variables
}
